#!/usr/bin/perl

use strict;
use warnings;

use CGI qw(:standard -nosticky -utf8 start_div end_div);
use JSON;
use OpenAPI::View qw(dereference);

my $filename = shift @ARGV;

open( my $inp, $filename );
my $api = decode_json( join '', <$inp> );
close $inp;

$api = dereference( $api, $api );

print header( -type => 'text/html',
              -expires => 'now',
              -charset => 'UTF-8' ),
      start_html( -title => $api->{info}{title} . ' v' .
                            $api->{info}{version} );

for my $path (sort keys %{$api->{paths}}) {
    print h1( $path );
    for my $operation ('get', 'post', 'patch', 'put', 'delete') {
        next if !$api->{paths}{$path}{$operation};
        print h2( $operation ),
              $api->{paths}{$path}{$operation}{description}
                ? p( $api->{paths}{$path}{$operation}{description} ) : '',
              start_form( -action => $path,
                          -method => $operation );
        for my $parameter (@{$api->{paths}{$path}{$operation}{parameters}}) {
            next if $parameter->{'$ref'}; # Will have to dereference later
            print h3( $parameter->{name} ),
                  $parameter->{description} ? p( $parameter->{description} ) : (),
                  input( { -type => 'text',
                           -name => $parameter->{name},
                           (exists $parameter->{example}
                                ? ( -placeholder => $parameter->{example} )
                                : ()) } );
        }
        print end_form;
    }
}

print end_html,
      "\n";
