#!/usr/bin/perl

use strict;
use warnings;

use JSON;
use OpenAPI::View::HTMLForms;

my $filename = shift @ARGV;

open( my $inp, $filename );
my $api = decode_json( join '', <$inp> );
close $inp;

$api = OpenAPI::View::HTMLForms->new( $api );

$api->show;
